export function portableCliHelpText(commandPrefix = '') {
  const command = String(commandPrefix || '').trim()
    || (String(process.argv[1] || '').replace(/\\/g, '/').includes('/bin/') ? 'node bin/tiinex-portable.mjs' : 'node tools/tiinex-portable.mjs');
  return [
    'Tiinex portable tooling',
    '',
    `${command} operations`,
    `${command} prepare-task [file|dir|zip] --task <read-schema|create-artifact|validate-draft|search-lineage|analyze-asset> [--schema <id>] [--host host-profile.json]`,
    `${command} discover-tooling [--host host-profile.json]`,
    `${command} plan-host-action <action> --host host-profile.json [--request request.json]`,
    `${command} accept-host-receipt --plan plan.json --receipt receipt.json`,
    `${command} list-material-providers [file|dir|zip] [--host host-profile.json]`,
    `${command} resolve-schema-material [file|dir|zip] --schema <schema-id> [--host host-profile.json]`,
    `${command} resolve-schema-chain-material [file|dir|zip] --schema <schema-id> [--depth 16]`,
    `${command} inspect <file|dir|zip> [--include-markdown]`,
    `${command} audit <file|dir|zip>`,
    `${command} resolve-lineage <file|dir|zip> [--start <id>] [--depth 3] [--direction ancestors|descendants|both]`,
    `${command} resolve-capabilities <schema-id> [capability]`,
    `${command} describe-schema-chain [file|dir|zip] --schema <schema-id>`,
    `${command} inspect-creation-contract <schema-id> [--transition <type>]`,
    `${command} make-writer-brief [file|dir|zip] --schema <schema-id>`,
    `${command} schema-guide [file|dir|zip] --schema <schema-id> [--task create] [--detail compact]`,
    `${command} read-schema-section [file|dir|zip] --schema <schema-id> --section "Artifact Creation Contract,Minimal Example"`,
    `${command} plan-artifact [file|dir|zip] --schema <schema-id> [--values inputs.json]`,
    `${command} process-live-turn [state.json] --turn turn-transaction.json [--material workspace.zip] --output state.json`,
    `${command} read-live-lineage [state.json]`,
    `${command} export-live-lineage [state.json] [--material workspace.zip] --bundle artifacts.zip [--require-interleaved]`,
    `${command} prepare-materialization [artifact-dir|zip] --proposals proposals.json`,
    `${command} create-local-artifact-set [artifact-dir|zip] --proposals proposals.json --output-dir <dir> [--bundle artifacts.zip]`,
    `${command} create-local-draft [schema-dir|zip] --schema <schema-id> --values inputs.json [--sections sections.json] --output artifact.md [--qualified-package artifact-evidence.zip --transfer-manifest manifest.json --bootstrap-manifest bootstrap/manifest.json --transfer-verification transfer.verify.json --bootstrap-verification bootstrap.verify.json --task-request task/request.md] [--created-at <iso>] [--authors <value>] [--references schema-references.json] [--overwrite]`,
    `${command} update-local-draft <draft.md> [schema-dir|zip] --replacement updated.md --schema <schema-id>`,
    `${command} delete-local-draft <draft.md> --confirm <draft-id-or-path> [--reason <text>]`,
    `${command} validate-draft <draft.md> [schema-dir|zip] --schema <schema-id>`,
    `${command} stage-draft <draft.md> [schema-dir|zip] --schema <schema-id>`,
    `${command} search-lineage <file|dir|zip> --query <text> [--schema <ids>] [--relation root|leaf] [--scope ancestors --start <id>]`,
    `${command} inspect-assets <file|dir|zip>`,
    `${command} prepare-asset-analysis <file|dir|zip> --asset <path> --host host-profile.json`,
    `${command} plan-durable-materialization --session session.json --specs materializations.json`,
    `${command} materialize-durable-findings [schema-dir|zip] --session session.json --specs materializations.json`,
    `${command} create-checkpoint session.json [--created-at <iso>]`,
    `${command} restore-checkpoint checkpoint.json`,
    `${command} build-runtime-package [file|dir|zip] [--session session.json] [--staged staged.json] [--output package.zip]`,
    `${command} inspect-runtime-package bundle.json`,
    `${command} rehydrate-runtime-package package.zip`,
    `${command} roundtrip-runtime-package [file|dir|zip] [--session session.json] [--bundle bundle.json]`,
    `${command} explain-findings <validation-result.json>`,
    `${command} repair-plan <validation-result.json>`,
    `${command} serialize-session <file|dir|zip>`,
    `${command} restore-session <snapshot.json>`,
    '',
    'All results are JSON. Remote schema reads are host-mediated and explicit. Operations do not mutate sources or authorize remote writes. Verified bootstrap package code is executable; separate supplied package code is never auto-executed.'
  ].join('\n');
}
