export function portableCliHelpText(commandPrefix = '') {
  const command = String(commandPrefix || '').trim()
    || (String(process.argv[1] || '').replace(/\\/g, '/').includes('/bin/') ? 'node bin/tiinex-portable.mjs' : 'node tools/tiinex-portable.mjs');
  return [
    'Tiinex portable tooling',
    '',
    'Common path (same command for humans and LLMs):',
    `${command} ground <handoff-package.zip> --route <Continue-from>`,
    `${command} ground <handoff-package.zip> --route <Continue-from> --continue <workspace-dir>`,
    `${command} author <workspace-dir> --schema <schema-id> --path <workspace-relative-artifact> --body <body.md> [--parent <workspace-relative-parent>] [--title <title>] [--summary <summary>] [--why <why>]`,
    `${command} handoff <workspace-dir>`,
    `Handoff aliases: ${command} orient <carrier.zip>; ${command} ground <carrier.zip> --route <Continue-from>; ${command} validate <carrier.zip>; ${command} handoff <workspace-dir>`,
    `Advanced/internal catalog: ${command} operations`,
    'Global option: append --phase-timing to emit monotonic in-process input/operation/materialization timing through the pre-serialization boundary; final JSON serialization/emission are explicitly unmeasured.',
    'After `ground --continue`, Tooling writes runtime-only `.tiinex/continuation.json` state beside the exact materialized source. Canonical manufacture excludes `.tiinex`. `author` uses that state to infer the qualified incoming Handoff Parent (or the previous authored result), seals c14n-v2 integrity, audits and stages the artifact, and keeps invalid output from becoming durable. After a qualified Handoff is authored, `handoff <workspace-dir>` infers its path, selected Workspace id/target, received package parent, unchanged sibling Workspace providers, canonical projected filename, and return output directory. Explicit low-level flags remain diagnostic/advanced overrides.',
    'Grounding option: broad directory reads quarantine .topics/development by default; append --include-legacy-topics to include that legacy subtree explicitly. `ground` keeps Required Context and current Task bodies out of the default receipt; append --include-required-context <requirement-id,name|all> and/or --include-current-work only when exact qualified body text is needed. After `grounded-to-act`, append --continue <workspace-dir> on the same ground command to project the exact current Task plus all Required Context and materialize the selected route Workspace exact bytes into an empty local directory. Use --workspace <id> with --materialize-workspace <workspace-dir> only when an explicitly carried non-selected Workspace is needed. For exact Parent recovery on the common path, bind the available exact-read tool with --host-tool <tool-name> and give Tooling one explicit state path with --state <file>. After executing the projected exact host action, return only the fetched UTF-8 content with --host-result <file|->; Tooling owns plan/receipt normalization, cumulative accepted recovery, and same-command resume. Advanced --host/--recovery plus plan-host-action/accept-host-receipt remain diagnostic escape hatches, not required happy-path knowledge.',
    'Output option: append --summary to inspect/audit/search-lineage/resolve-lineage/qualify-cold-start for a bounded receipt. For qualify-cold-start, append --include-required-context <requirement-id,name|all> only when exact qualified Required Context body text must be projected.',
    `${command} prepare-task [file|dir|zip] --task <read-schema|create-artifact|validate-draft|search-lineage|analyze-asset> [--schema <id>] [--host host-profile.json]`,
    `${command} discover-tooling [--host host-profile.json]`,
    `${command} describe-cold-start-ingress [routed-handoff-package|workspace-bootstrap|degraded-capture]`,
    `${command} project-cold-start-host [--ingress routed-handoff-package|workspace-bootstrap] [--host host-profile.json]`,
    `${command} ground <handoff-package.zip> --route <Continue-from> [--continue <workspace-dir>] [--include-current-work] [--include-required-context <requirement-id,name|all>] [--materialize-workspace <workspace-dir> --workspace <id>] [--host-tool <exact-read-tool> --state <tooling-state.json> [--host-result <file|->]] [--include-legacy-topics]`,
    `${command} ground-cold-consumer [handoff-package.zip] [--route <route>] [--host host-profile.json] [--interaction interaction.json] [--participants participants.json] [--contributions contributions.json] [--role-material role.trace.md]`,
    `${command} qualify-cold-start <handoff-package.zip> --route <Continue-from> --pre-takeover minimal-bootstrap-only|none|native-archaeology [--evidence-source caller-declared|external-observer|host-instrumented]`,
    `${command} qualify-cold-start --evidence evidence.json [--ingress routed-handoff-package|workspace-bootstrap|degraded-capture]`,
    `${command} plan-host-action <action> --host host-profile.json [--request request.json]`,
    `${command} accept-host-receipt --plan plan.json --receipt receipt.json [--prior previous-accepted.json]`,
    `${command} list-material-providers [file|dir|zip] [--host host-profile.json]`,
    `${command} resolve-schema-material [file|dir|zip] --schema <schema-id> [--host host-profile.json]`,
    `${command} resolve-schema-chain-material [file|dir|zip] --schema <schema-id> [--depth 16]`,
    `${command} inspect <file|dir|zip> [--include-markdown]`,
    `${command} audit <file|dir|zip>`,
    `${command} project-operating-overview <file|dir|zip>`,
    `${command} resolve-lineage <file|dir|zip> [--start <id>] [--depth 3] [--direction ancestors|descendants|both]`,
    `${command} resolve-capabilities <schema-id> [capability]`,
    `${command} describe-schema-chain [file|dir|zip] --schema <schema-id>`,
    `${command} inspect-creation-contract <schema-id> [--transition <type>]`,
    `${command} make-writer-brief [file|dir|zip] --schema <schema-id>`,
    `${command} schema-guide [file|dir|zip] --schema <schema-id> [--task create] [--detail compact]`,
    `${command} read-schema-section [file|dir|zip] --schema <schema-id> --section "Artifact Creation Contract,Minimal Example"`,
    `${command} plan-artifact [file|dir|zip] --schema <schema-id> [--values inputs.json]`,
    `${command} process-live-turn [state.json] --turn turn-transaction.json [--material workspace.zip] --output state.json`,
    `${command} read-live-lineage [state.json]`,
    `${command} export-live-lineage [state.json] [--material workspace.zip] --bundle artifacts.zip [--require-interleaved]`,
    `${command} prepare-materialization [artifact-dir|zip] --proposals proposals.json`,
    `${command} create-local-artifact-set [artifact-dir|zip] --proposals proposals.json --output-dir <dir> [--bundle artifacts.zip]`,
    `${command} create-local-draft [schema-dir|zip] --schema <schema-id> --values inputs.json [--sections sections.json] --output artifact.md [--qualified-package artifact-evidence.zip --transfer-manifest manifest.json --bootstrap-manifest bootstrap/manifest.json --transfer-verification transfer.verify.json --bootstrap-verification bootstrap.verify.json --task-request task/request.md] [--created-at <iso>] [--authors <value>] [--references schema-references.json] [--overwrite]`,
    `${command} update-local-draft <draft.md> [schema-dir|zip] --replacement updated.md --schema <schema-id>`,
    `${command} delete-local-draft <draft.md> --confirm <draft-id-or-path> [--reason <text>]`,
    `${command} validate-draft <draft.md> [schema-dir|zip] --schema <schema-id>`,
    `${command} stage-draft <draft.md> [schema-dir|zip] --schema <schema-id>`,
    `${command} search-lineage <file|dir|zip> --query <text> [--schema <ids>] [--relation root|leaf] [--scope ancestors --start <id>]`,
    `${command} inspect-assets <file|dir|zip>`,
    `${command} prepare-asset-analysis <file|dir|zip> --asset <path> --host host-profile.json`,
    `${command} plan-durable-materialization --session session.json --specs materializations.json`,
    `${command} materialize-durable-findings [schema-dir|zip] --session session.json --specs materializations.json`,
    `${command} create-checkpoint session.json [--created-at <iso>]`,
    `${command} restore-checkpoint checkpoint.json`,
    `${command} manufacture-handoff-package <workspace-dir> --handoff <workspace-relative-handoff.trace.md> --workspace-id <id> --workspace-target <exact-workspace-relative-.workspace.md> (--output <exact-tooling-projected-filename> | --output-dir <dir>) [--additional-workspaces <id=dir,id=dir> | --workspace-roots workspaces.json] [--handoff-routes <path1,path2> | --workspace-routes routes.json] [--route <selected-path-or-route-id>] [--legacy-recipient-v2-compatibility] [--collision-instance 2] [--transport-text [sidecar.txt]] [--tooling-bootstrap embedded|persistent] [--tooling-bootstrap-manifest verified-bootstrap.json] [--material-bindings bindings.json] [--package-parent <previous.handoff-package.zip>] [--package-major --major-reason <milestone>] [--no-roundtrip]`,
    `${command} project-handoff-carrier-output <handoff-package.zip> [--route <workspace-relative-handoff.trace.md|route-id>] [--collision-instance 2]`,
    'Handoff human return: when ready, emit only humanOutput.primary as the sole package choice plus the exact humanOutput.normalInlineRouting.content adjacent to it in a copyable surface. If the chat host supports fenced code blocks, render those exact routing bytes in a fenced code block; otherwise use an equivalent copyable host surface. Do not add semantic work-summary prose, humanOutput JSON, helper artifacts, manually reconstructed routing, or duplicate normal file choices unless the user explicitly asks for explanation/review evidence. Presentation wrappers have no semantic authority; --transport-text is optional fallback only.',
    `${command} orient-handoff-package <handoff-package.zip>`,
    `${command} audit-handoff-package-context <handoff-package.zip>`,
    `${command} build-runtime-package [file|dir|zip] [--session session.json] [--staged staged.json] [--output package.zip]`,
    `${command} inspect-runtime-package bundle.json`,
    `${command} rehydrate-runtime-package package.zip`,
    `${command} roundtrip-runtime-package [file|dir|zip] [--session session.json] [--bundle bundle.json]`,
    `${command} explain-findings <validation-result.json>`,
    `${command} repair-plan <validation-result.json>`,
    `${command} serialize-session <file|dir|zip>`,
    `${command} restore-session <snapshot.json>`,
    '',
    'All results are JSON. Remote schema reads are host-mediated and explicit. Operations do not mutate sources or authorize remote writes. Verified bootstrap package code is executable; separate supplied package code is never auto-executed.'
  ].join('\n');
}
