const tests = [
  './input/portable.input.test.mjs',
  './input/node.input.test.mjs',
  './portable.engine.test.mjs',
  './operation.catalog.test.mjs',
  './bootstrap/bootstrap.test.mjs',
  './host/host.capabilities.test.mjs',
  './host/tool.bindings.test.mjs',
  './orchestration/task.prepare.test.mjs',
  './providers/schema.providers.test.mjs',
  './schema/schema.guide.test.mjs',
  './schema/contract.foundation.test.mjs',
  './schema/contract.project.test.mjs',
  './schema/contract.field-domain.test.mjs',
  './schema/contract.machine-shape.test.mjs',
  './schema/schema.snapshot.machine-shape.test.mjs',
  './schema/contract.ordinary-fields.test.mjs',
  './schema/contract.ordinary-fields.canonical.test.mjs',
  './lineage/lineage.search.test.mjs',
  './draft/draft.operations.test.mjs',
  './draft/draft.create.test.mjs',
  './live/live.lineage.test.mjs',
  './adapters/cli/cli.local-output.test.mjs',
  './adapters/cli/cli.run.test.mjs',
  './assets/asset.operations.test.mjs',
  './session/portable.session.test.mjs',
  './materialization/durable.materialize.test.mjs',
  './checkpoint/portable.checkpoint.test.mjs',
  './package/runtime.package.test.mjs',
  './handoff/carrierProjection.test.mjs',
  './handoff/humanOutputNormalEmission.test.mjs',
  './handoff/coldConsumerEntrypoint.test.mjs',
  './handoff/handoff.manufacture.test.mjs',
  './handoff/multiRootManufacture.test.mjs',
  './handoff/pointerEntrypoint.test.mjs',
  './handoff/contextAudit.test.mjs',
  './package/semantic.package.test.mjs',
  './package/semantic.package.authority-closure.test.mjs',
  './conformance/checkpoint.qualification.test.mjs',
  './adapters/node/checkpoint.verify.test.mjs'
];

for (const test of tests) await import(test);

console.log('✓ portable tooling aggregate suite passed');
