import assert from 'node:assert/strict';
import { buildPublicationPlan, buildPublicationResult } from '../publication/publication.contract.js';
import { stateWithWorkspacePublicationReceipt } from './workspace.publicationReceipts.js';
import './workspace.persistence.js';

const markdown = '# Continuity Context\n\n- Envelope Schema: [tiinex.root.v1](tiinex.root.v1.schema.md)\n- Current\n  - Current Schema: [tiinex.topic.v1](tiinex.topic.v1.schema.md)\n  - Created At: 2026-08-19T00:00:00.000Z\n  - Summary: Guided publication fixture\n  - Status: draft/local\n\n---\n\n# Guided publication fixture\n\nReadable exact local payload.\n\n# Continuity Integrity\n\n- Draft Local Integrity\n  - Method: browser-local-draft\n  - Value: pending-publication-or-export\n';
const local = { id: 'local-1', title: 'Local', path: 'local.trace.md', markdown, schemaId: 'tiinex.topic.v1', sourceMode: 'local-transition', source: { adapterId: 'local' } };
const source = { id: 'source-1', title: 'Source', path: 'source.trace.md', markdown: '# source', sourceMode: 'source-backed', source: { adapterId: 'github', repo: 'Tiinex/docs', ref: 'main' } };
const state = { version: 1, activeWorkspaceId: 'w', view: {}, workspaces: [{ id: 'w', title: 'W', name: 'W', records: [local, source], assets: [], sources: [], importLog: [] }] };
const plan = buildPublicationPlan(state.workspaces[0], { recordId: local.id, mutationPolicy: 'create-new', destination: { provider: 'github', repository: 'Tiinex/docs', targetKind: 'github.issue.body' } });
const targetA = 'https://github.com/Tiinex/docs/issues/12';
const targetB = 'https://github.com/Tiinex/docs/issues/13';
const result = buildPublicationResult(plan, { state: 'success', verificationStatus: 'verified', verifiedPayloadSha256: plan.outboundPayload.sha256, sourceTarget: { adapterId: 'github', targetKind: 'github.issue.body', inputTarget: targetA } });
assert.equal(result.status, 'success');
const attestation = { schema: 'tiinex.site.githubPublicationHumanMutationAttestation.v2', type: 'human-github-web-mutation-confirmation', planSha256: plan.planSha256, mutationTarget: { provider: 'github', targetKind: 'github.issue.body', inputTarget: targetA, repository: 'Tiinex/docs', issueNumberLexeme: '12', commentId: '', issueTarget: targetA }, confirmedAt: '2026-08-19T11:59:59.000Z', boundary: 'Human confirmed exact plan + exact target; Tiinex did not perform a hidden/API write.' };
const beforeLocal = JSON.stringify(local); const beforeSource = JSON.stringify(source);
assert.equal(stateWithWorkspacePublicationReceipt(state, 'w', result).ok, false, 'receipt needs target-bound execution evidence');
assert.equal(stateWithWorkspacePublicationReceipt(state, 'w', result, { executionAttestation: { ...attestation, planSha256: 'stale' } }).ok, false, 'stale plan evidence rejected');
assert.equal(stateWithWorkspacePublicationReceipt(state, 'w', result, { executionAttestation: { ...attestation, mutationTarget: { ...attestation.mutationTarget, inputTarget: targetB, issueNumberLexeme: '13', issueTarget: targetB } } }).ok, false, 'result target A cannot pair with attestation target B');
const applied = stateWithWorkspacePublicationReceipt(state, 'w', result, { executionAttestation: attestation, clock: () => Date.parse('2026-08-19T12:00:00Z') });
assert.equal(applied.ok, true);
assert.equal(applied.workspace.publicationReceipts.length, 1);
assert.equal(applied.workspace.publicationReceipts[0].executionAttestation.planSha256, plan.planSha256);
assert.equal(applied.workspace.publicationReceipts[0].executionAttestation.mutationTarget.inputTarget, targetA);
assert.equal(applied.workspace.publicationReceipts[0].executionAttestation.mutationTarget.issueNumberLexeme, '12');
assert.match(applied.workspace.publicationReceipts[0].executionAttestation.boundary, /Tiinex did not perform/i);
assert.equal(JSON.stringify(applied.workspace.records.find((r) => r.id === local.id)), beforeLocal);
assert.equal(JSON.stringify(applied.workspace.records.find((r) => r.id === source.id)), beforeSource);
const delta = globalThis.TiinexWorkspacePersistence.createLocalDeltaState(applied.state);
assert.equal(delta.workspaces[0].publicationReceipts.length, 1, 'publication receipt survives durable local-delta projection');
const roundTrip = JSON.parse(JSON.stringify(delta));
assert.equal(roundTrip.workspaces[0].publicationReceipts[0].sourceBinding.remoteTarget.inputTarget, targetA);
assert.equal(roundTrip.workspaces[0].publicationReceipts[0].executionAttestation.mutationTarget.inputTarget, targetA, 'exact target-bound execution evidence survives reopen');
assert.equal(roundTrip.workspaces[0].records.find((r) => r.id === local.id).source.adapterId, 'local');
assert.equal(state.workspaces[0].publicationReceipts, undefined, 'input state stays unchanged');
console.log('workspace.publicationReceipts: PASS');
