import assert from 'node:assert/strict';
import { buildWorkspaceMaterialLedger, materialLedgerSourceReceipt } from './workspace.materialLedger.js';

const source = { id: 'github:tiinusen-socials', adapterId: 'github', label: 'Tiinusen/socials' };
const records = [{ id: 'workspace-record', title: 'Workspace', kind: 'tiinex.workspace.v1', schemaId: 'tiinex.workspace.v1', path: '.topics/000.workspace.md', source, workspaceArtifactRole: { schema: 'tiinex.workspace.artifact.role.v1', openEligible: true, mergeEligible: true } }, { id: 'parent', title: 'Parent', kind: 'tiinex.topic.v1', schemaId: 'tiinex.topic.v1', path: '.topics/parent.trace.md', source }, { id: 'child', title: 'Child', kind: 'tiinex.topic.v1', schemaId: 'tiinex.topic.v1', path: '.topics/child.trace.md', trace: '.topics/parent.trace.md', source }, { id: 'schema', title: 'Schema', kind: 'tiinex.schema.v1', schemaId: 'tiinex.schema.v1', path: 'tiinex.topic.v1.schema.md', sourceMode: 'supporting', source }, { id: 'local-shadow', title: 'Child', kind: 'tiinex.topic.v1', schemaId: 'tiinex.topic.v1', path: '.topics/child.trace.md', source: { id: 'local', adapterId: 'local', kind: 'local-session' }, materialReconciliation: { status: 'local-shadowed-by-source', sourceId: source.id } }];
const workspace = { id: 'w', records, assets: [] };
const ledger = buildWorkspaceMaterialLedger(workspace, { displayOptions: { leavesOnly: true, showSupportingMarkdown: false, showWorkspaceArtifacts: true } });
assert.equal(ledger.counts.rawRecords, 5, 'ledger keeps raw record count separate from visible count');
assert(ledger.counts.visibleRecords < ledger.counts.rawRecords, 'ledger should expose visibility reductions instead of losing material');
assert.equal('rawWorkspaceCandidates' in ledger.counts, false, 'canonical runtime ledger exposes no legacy candidate count');
assert.equal(ledger.counts.rawWorkspaceArtifacts, 1, 'workspace artifacts are counted from the canonical record spine');
assert.equal(ledger.counts.lineageUsableRecords, 5, 'hidden records remain lineage-usable material');
assert.equal(ledger.counts.groupedRecords, 1, 'source+local grouped records are accounted for separately from display-hidden records');
assert.equal(ledger.hiddenRecordsByReason['hidden-local-shadowed-by-source'], 1, 'hidden reasons are counted once per record, not once per identity key');
assert.equal(ledger.recordsBySource[source.id], 4, 'ledger tracks records by source id');
assert.equal(ledger.workspaceArtifactsBySource[source.id], 1, 'ledger tracks workspace artifacts by source id on the record spine');
assert.equal('workspaceCandidatesBySource' in ledger, false, 'canonical ledger exposes no candidate source map');
const receipt = materialLedgerSourceReceipt(workspace, source.id, { rawAdapterRecords: 3 }, { displayOptions: { leavesOnly: true } });
assert.equal(receipt.rawAdapterRecords, 3, 'source receipt preserves raw adapter records');
assert.equal(receipt.sourceRecords, 4, 'source receipt preserves inserted source records independently of visibility');
assert.equal(receipt.visibleSourceRecords, 2, 'source receipt explains source-backed records visible in the current discovery view');
assert.equal(receipt.hiddenSourceRecords, 2, 'source receipt explains source-backed records hidden by display/leaf membership');
assert.equal(receipt.sourceWorkspaceArtifacts, 1, 'source receipt exposes source-backed workspace artifacts from canonical records');
assert.equal('sourceWorkspaceCandidates' in receipt, false, 'source receipt does not recreate a parallel candidate model');
console.log('workspace.materialLedger: ok');
