import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faArrowLeft,
  faArrowRight,
  faArrowUpFromBracket,
  faCircleNodes,
  faCircleCheck,
  faCirclePlus,
  faCloudArrowUp,
  faCodeBranch,
  faCompass,
  faPenToSquare,
  faFileArrowUp,
  faFileCode,
  faFolder,
  faDownload,
  faDownLeftAndUpRightToCenter,
  faFolderOpen,
  faFolderPlus,
  faHandPointer,
  faSliders,
  faHouse,
  faLink,
  faListCheck,
  faMagnifyingGlass,
  faQuestion,
  faQuoteRight,
  faShareNodes,
  faSitemap,
  faTriangleExclamation,
  faTrashCan,
  faUpRightFromSquare,
  faUpRightAndDownLeftFromCenter,
  faXmark
} from '@fortawesome/free-solid-svg-icons';
import { faCircle, faFileLines } from '@fortawesome/free-regular-svg-icons';

const ICONS = {
  add: faCirclePlus,
  archive: faFolder,
  audit: faCircleCheck,
  check: faCircleCheck,
  asset: faFileLines,
  close: faXmark,
  collapse: faDownLeftAndUpRightToCenter,
  continue: faCodeBranch,
  create: faCirclePlus,
  delete: faTrashCan,
  download: faDownload,
  drop: faCloudArrowUp,
  edit: faPenToSquare,
  expand: faUpRightAndDownLeftFromCenter,
  faCodeBranch,
  fileUpload: faFileArrowUp,
  filters: faSliders,
  folderDownload: faDownload,
  folderOpen: faFolderOpen,
  folderPlus: faFolderPlus,
  github: faCircleNodes,
  handPointer: faHandPointer,
  interpret: faArrowRight,
  help: faQuestion,
  faQuoteRight,
  home: faHouse,
  lineage: faCodeBranch,
  local: faFolder,
  markdown: faFileCode,
  manualFiles: faFileLines,
  multiverse: faCompass,
  next: faArrowRight,
  noNodes: faCircle,
  open: faFileLines,
  previous: faArrowLeft,
  reference: faQuoteRight,
  search: faMagnifyingGlass,
  share: faShareNodes,
  shareNodes: faShareNodes,
  source: faUpRightFromSquare,
  task: faListCheck,
  tree: faSitemap,
  upload: faArrowUpFromBracket,
  warning: faTriangleExclamation,
  workspace: faCircleNodes
};

export function Icon({ name, className = '', ...props }) {
  const icon = ICONS[name] || faCircle;
  return <FontAwesomeIcon className={`tx-icon ${className}`.trim()} icon={icon} aria-hidden="true" {...props} />;
}
