import assert from 'node:assert/strict';
import '../workspaces/workspace.route.js';
import { buildExactStateUrl, projectShareTruth, ShareScope } from './shareProjection.js';
import { stateWithWorkspaceViewPatch } from './workspaceMulticolumn.js';
import { timePortalWithIntent, timePortalWithResolvedSnapshot } from '../workspaces/workspace.timePortal.js';

const commit = 'c'.repeat(40);
const workspace = { id:'w1', title:'Docs', sources:[{ id:'github:docs', adapterId:'github', repo:'owner/repo', ref:'main', materializedCommit:'a'.repeat(40), rootPath:'.topics' }], records:[], assets:[] };
const latest = { activeWorkspaceId:'w1', workspaces:[workspace], view:{ universe:'column', workspaceVerse:'feed', reader:'scan', query:'' }, workspaceViews:{} };
const intentView = timePortalWithIntent(latest.view,{ begin:'2026-05-01T10:00', end:'2026-05-31T22:40', sourceId:'github:docs', snapshotInput:'old-ref' });
const unresolved = stateWithWorkspaceViewPatch(latest,'w1',intentView);
const unresolvedRoute = globalThis.TiinexWorkspaceRoute.makeRouteState(unresolved);
assert.equal(unresolvedRoute.view.timePortal.mode,'intent');
assert.equal(unresolvedRoute.view.timePortal.snapshot,undefined,'unresolved route intent must remain unresolved');
const historicalView = timePortalWithResolvedSnapshot(intentView,{ sourceId:'github:docs',repository:'owner/repo',rootPath:'.topics',requestedRef:'old-ref',resolvedRef:'old-ref',materializedCommit:commit,inputTarget:'old-ref',resolvedBy:'github.commit-resolution' });
const historical = stateWithWorkspaceViewPatch(latest,'w1',historicalView);
const route = globalThis.TiinexWorkspaceRoute.makeRouteState(historical);
assert.equal(route.view.timePortal.snapshot.materializedCommit,commit,'route preserves exact immutable historical representation');
assert.equal(route.workspaces[0].sources[0].materializedCommit,'a'.repeat(40),'route keeps live/latest source receipt distinct from historical commit');
const normalized = globalThis.TiinexWorkspaceRoute.normalizeRouteState(route);
assert.equal(normalized.view.timePortal.snapshot.materializedCommit,commit);
const persistenceCodec={ encodeState:(value)=>Buffer.from(JSON.stringify(value),'utf8').toString('base64url') };
const exactUrl=buildExactStateUrl(historical,{baseUrl:'https://viewer.example/app',routeCodec:globalThis.TiinexWorkspaceRoute,persistenceCodec});
const encoded=new URL(exactUrl).hash.replace(/^#state=/,'');
const decoded=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8'));
assert.equal(decoded.view.timePortal.snapshot.materializedCommit,commit,'exact-state share carries resolved historical commit');
assert.equal(decoded.historicalReads,undefined,'transient historical bytes/read-model are not serialized into semantic route/share state');
const projection=projectShareTruth({scope:ShareScope.current,state:historical,exactStateBaseUrl:'https://viewer.example/app',routeCodec:globalThis.TiinexWorkspaceRoute,persistenceCodec});
assert.equal(projection.exactStateUrl,exactUrl);
assert.equal(globalThis.TiinexWorkspaceRoute.makeRouteState(latest).view.timePortal,undefined,'latest route contains no stale historical identity');
console.log('timePortalRouteShare: ok');
