import assert from 'node:assert/strict';
import '../sources/source.identity.js';
import '../workspaces/workspace.lifecycle.js';
import { createRecordFromMarkdown } from '../artifacts/artifact.record.js';
import { runWorkspaceSourceCloseCommand } from './workspaceSourceCloseCommand.js';

const lifecycle = globalThis.TiinexWorkspaceLifecycle;
const created = lifecycle.createWorkspace(lifecycle.makeEmptyAppState(), { name: 'Close source' }, { clock: () => '2026-08-09T00:00:00.000Z' });
const local = lifecycle.addWorkspaceRecord(created.state, created.workspace.id, createRecordFromMarkdown('# Local\n\nBody', { path: 'local.md', sourceMode: 'manual-file' }));
const source = lifecycle.addWorkspaceSource(local.state, created.workspace.id, { id: 'github:docs', label: 'Docs', repository: 'Tiinex/docs', rootPath: '.topics' });
const sourceRec = createRecordFromMarkdown('# Source\n\nBody', { path: '.topics/source.md', sourceMode: 'source' });
const withSourceRecord = lifecycle.addWorkspaceSourceRecords(source.state, created.workspace.id, source.source.id, [sourceRec]);
const closed = runWorkspaceSourceCloseCommand({ lifecycle, state: withSourceRecord.state, workspaceId: created.workspace.id, sourceId: source.source.id });
assert.equal(closed.ok, true, closed.error);
assert.equal(closed.notice, 'Source closed.');
const workspace = lifecycle.activeWorkspace(closed.state);
assert(!workspace.records.some((record) => record.source?.id === source.source.id), 'source-backed records are removed on close');
assert(workspace.records.some((record) => record.source?.id === 'local' || record.source?.kind === lifecycle.SESSION_SOURCE_KIND), 'local/session records are preserved on source close');
const clearLocal = runWorkspaceSourceCloseCommand({ lifecycle, state: closed.state, workspaceId: created.workspace.id, sourceId: 'local' });
assert.equal(clearLocal.ok, true, clearLocal.error);
assert.match(clearLocal.notice, /Cleared Local session material/);
const clearedWorkspace = lifecycle.activeWorkspace(clearLocal.state);
assert.equal(clearedWorkspace.records.some((record) => record.source?.id === 'local' || record.source?.kind === lifecycle.SESSION_SOURCE_KIND), false);
assert(clearedWorkspace.sources.some((item) => item.id === 'local'), 'Local source row stays available after clearing local material');
console.log('workspaceSourceCloseCommand: ok');
