import assert from 'node:assert/strict';
import fs from 'node:fs';
import '../workspaces/workspace.route.js';
import { resolveTimePortalSnapshot } from '../app/timePortalSnapshotResolution.js';
import { historicalWorkspaceForReadModel, loadTimePortalHistoricalReadModel } from '../app/timePortalHistoricalRead.js';
import { normalizeTimePortalView, timePortalWithIntent, timePortalWithResolvedSnapshot } from '../workspaces/workspace.timePortal.js';

const liveCommit='a'.repeat(40), historicalCommit='b'.repeat(40);
const liveSource={ id:'github:docs', adapterId:'github', sourceKind:'github.repo', kind:'github-tree', label:'Docs', repo:'owner/repo', ref:'main', materializedCommit:liveCommit, rootPath:'.topics', repoDiscovery:true, explicitFileRefs:[], config:{repo:'owner/repo',ref:'main',rootPath:'.topics'} };
const liveRecord={id:'live:A',title:'Live A',path:'.topics/live-a.trace.md',markdown:'# Live A',source:{...liveSource},sourceTarget:{inputTarget:'.topics/live-a.trace.md',materializedCommit:liveCommit}};
const localDraft={id:'local:draft',title:'Local draft',path:'draft.trace.md',markdown:'# Draft',source:{id:'local',adapterId:'local'}};
const workspace={id:'w1',title:'Docs',sources:[{id:'local',adapterId:'local'},liveSource],records:[liveRecord,localDraft],assets:[]};
const original=JSON.stringify(workspace);
const intent=timePortalWithIntent({workspaceVerse:'feed'},{begin:'2026-05-01T10:00',end:'2026-05-31T22:40',sourceId:'github:docs',snapshotInput:historicalCommit});
assert.equal(normalizeTimePortalView(intent.timePortal).mode,'intent');
const resolution=await resolveTimePortalSnapshot({workspace,view:intent,snapshotInput:historicalCommit,fetchImpl:async()=>{throw new Error('exact commit must not resolve over network');}});
assert.equal(resolution.ok,true);
assert.equal(resolution.snapshot.materializedCommit,historicalCommit);
const historicalView=timePortalWithResolvedSnapshot(intent,resolution.snapshot);
assert.equal(historicalView.timePortal.snapshot.materializedCommit,historicalCommit);
assert.equal(liveSource.materializedCommit,liveCommit,'historical selection must not rewrite live source receipt');
const treeUrl=`https://api.github.com/repos/owner/repo/git/trees/${historicalCommit}?recursive=1`;
const rawUrl=`https://raw.githubusercontent.com/owner/repo/${historicalCommit}/.topics/history.trace.md`;
const read=await loadTimePortalHistoricalReadModel({workspace,snapshot:resolution.snapshot,fetchImpl:async(url)=>{
 if(url===treeUrl)return{ok:true,json:async()=>({truncated:false,tree:[{type:'blob',path:'.topics/history.trace.md'}]})};
 if(url===rawUrl)return{ok:true,text:async()=> '# Historical B\n\nExact old source.'};
 return{ok:false,status:404,statusText:'Not Found',json:async()=>({message:'missing'}),text:async()=>''};
},options:{allowCache:false}});
assert.equal(read.state,'loaded');
assert.equal(JSON.stringify(workspace),original,'historical B cannot redefine live/latest A or local drafts');
const shell=historicalWorkspaceForReadModel(workspace,read);
assert.equal(shell.records.length,1);
assert.equal(shell.records[0].sourceTarget.materializedCommit,historicalCommit);
assert.equal(shell.records.some((record)=>record.id==='live:A'),false,'historical shell cannot silently show live A as historical');
assert.equal(shell.records.some((record)=>record.id==='local:draft'),false,'local draft is not projected into historical source review');
assert.equal(workspace.records.some((record)=>record.id==='local:draft'),true,'local draft remains intact in live workspace');
assert.equal(shell.sources[0].closeable,false);
assert.equal(shell.sources[0].loadable,false);
assert.equal(shell.records[0].sourceMode,'source-backed-historical');

const appSource=fs.readFileSync(new URL('../app/TiinexApp.jsx',import.meta.url),'utf8');
assert.match(appSource,/loadHistoricalSnapshot\(workspace\.id\)/,'historical fetch remains explicit behind product action');
const routeHandler=appSource.slice(appSource.indexOf('const onRoute ='),appSource.indexOf("window.addEventListener('popstate'"));
assert.doesNotMatch(routeHandler,/loadHistoricalSnapshot|resolveTimePortalSnapshot|materializeGithubSource/,'semantic route restore must stay network-silent for Time Portal');
const surfaceSource=fs.readFileSync(new URL('../schemas/workspace/workspace.views.jsx',import.meta.url),'utf8');
assert.match(surfaceSource,/!readOnlyHistorical && \(verse === 'feed' \|\| verse === 'lineage'\)/,'historical presentation must not prepare canonical mutation actions');
assert.match(surfaceSource,/readOnly=\{readOnlyHistorical\}/,'historical cards/tree are explicitly read-only');
const displaySource=fs.readFileSync(new URL('../schemas/workspace/workspace.displayOptions.views.jsx',import.meta.url),'utf8');
assert.match(displaySource,/Time Portal/);
assert.match(displaySource,/no date is converted into a commit/);
console.log('post-v437 M0-E Time Portal product parity closure: PASS');
