import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const plan = read('export/export.plan.js');
const controller = read('schemas/workspace/workspace.exportDialog.controller.jsx');
const view = read('schemas/workspace/workspace.exportDialog.views.jsx');
const product = read('app/workspaceGithubPublication.js');
const command = read('app/workspaceExportExecutionCommand.js');
const snapshot = read('adapters/github/github.issueSnapshot.js');
const publicationRead = read('adapters/github/github.publicationRead.js');
const readTransport = read('adapters/github/github.readTransport.js');
const persistence = read('workspaces/workspace.persistence.js');
assert.ok(plan.includes("status: 'available'") && plan.includes('Exact issue / issue-comment'), 'GitHub social publication must no longer be stale future/Case C UI');
assert.ok(plan.includes("action: 'guided-github-publication'"), 'export plan exposes guided routine, not hidden write');
assert.ok(command.includes('github-publication.guided-routine-required'), 'generic export command must not simulate a provider write');
assert.ok(product.includes('buildPublicationPlan') && product.includes('buildPublicationResult'), 'Site consumes shared plan/result authority directly');
assert.ok(product.includes('parseExactGithubIssueTarget'), 'final target uses accepted exact shared parser');
assert.equal(product.includes('parseGithubIssueSnapshotTarget'), false, 'permissive issue snapshot parser must not qualify publication targets');
assert.ok(publicationRead.includes('readExactGithubIssuePublicationRepresentation'), 'bounded GitHub read sibling exposes exact post-write body observation');
assert.equal(publicationRead.includes('parseGithubIssueSnapshotTarget'), false, 'verification read owner receives already-qualified target and does not use permissive snapshot parsing');
assert.ok(publicationRead.includes('fetchGithubJson') && snapshot.includes('fetchGithubJson') && readTransport.includes('export async function fetchGithubJson'), 'publication verification and issue snapshots share one read-only GitHub JSON transport owner');
assert.ok(controller.includes('copiedPlanSha256') && controller.includes('verificationPlanSha256'), 'transient completion is bound to exact plan identity');
assert.ok(controller.includes('buildWorkspaceGithubPublicationPreflight') && controller.includes('publicationPreflight'), 'shared publication preflight is memoized per workspace/GitHub selection rather than rebuilt on each form input');
assert.ok(view.includes('Copy exact payload') && view.includes('Open GitHub') && view.includes('Verify exact publication'), 'guided routine remains visible and ordered');
assert.ok(view.includes('Final exact GitHub URL'), 'create-new/comment completion requires exact result target');
assert.ok(persistence.includes('publicationReceipts'), 'qualified local receipt has durable local-delta owner');
assert.equal(product.includes('fetch('), false, 'Site product owner must not add a second GitHub fetch implementation');
assert.equal(product.includes('api.github.com'), false, 'Site product owner must not construct GitHub API URLs');
assert.equal(controller.includes('api.github.com'), false);
assert.equal(view.includes('api.github.com'), false);
assert.equal(controller.includes('Issue #3'), false);
assert.equal(product.includes('Tiinusen'), false);
console.log('postV447M0FGithubSocialPublicationProductIntegration: PASS');
