import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const product = read('app/workspaceGithubPublication.js');
const controller = read('schemas/workspace/workspace.exportDialog.controller.jsx');
const view = read('schemas/workspace/workspace.exportDialog.views.jsx');
const receipt = read('workspaces/workspace.publicationReceipts.js');
const shared = read('publication/publication.contract.js');
const tooling = read('tooling/portable/publication/runtime.publication.js');
assert.ok(product.includes('confirmWorkspaceGithubPublicationMutation') && product.includes('human-github-web-mutation-confirmation'), 'Site owns explicit human mutation attestation only');
assert.ok(product.includes('publication.verify.human-mutation-attestation-required'), 'direct verification owner fails closed before shared success without attestation');
assert.ok(product.includes('qualifiedHumanMutationAttestation') && product.includes('planSha256'), 'attestation is tied to exact plan identity');
assert.ok(controller.includes('mutationAttestation') && controller.includes('onPublicationAttest'), 'controller carries explicit attestation state separately from Copy/Open');
assert.ok(view.includes('I posted/updated this exact payload at this exact GitHub target') && view.includes('Copy/Open alone never count as publication success'), 'guided flow makes human mutation confirmation explicit');
assert.ok(view.includes('!progress.attested'), 'Verify remains gated on current-plan attestation at UI boundary');
assert.ok(receipt.includes('executionAttestation') && receipt.includes('Tiinex did not perform a hidden/API write'), 'durable Site-local receipt explains human-guided execution evidence');
assert.ok(shared.includes('export function buildPublicationResult'), 'shared buildPublicationResult remains success/result authority');
assert.equal(tooling.includes('human-github-web-mutation-confirmation'), false, 'Tooling portable contract remains untouched by Site UI attestation');
assert.equal(product.includes('api.github.com'), false, 'no hidden GitHub write/API was introduced');
console.log('postV448M0FHumanMutationEvidenceClosure: PASS');
